# This is an evgen configuration file.
# Refer to config/README.md for more info.

map_width: 15
map_height: 10
starting_foliage: 10
energy_gain: 5
daily_foliage_growth: 3
starting_animals: 20
starting_energy: 30
min_procreation_energy: 15
procreation_energy_loss: 10
min_mutations: 0
max_mutations: 5
genome_length: 10

map_variant: globe
foliage_variant: equator
mutation_variant: random
behaviour_variant: predestined
