# This is an evgen configuration file.
# Refer to config/README.md for more info.

map_width: 50
map_height: 50
starting_foliage: 5000
energy_gain: 5000
daily_foliage_growth: 5000
starting_animals: 100
starting_energy: 5000
min_procreation_energy: 100
procreation_energy_loss: 100
min_mutations: 100
max_mutations: 100
genome_length: 100

map_variant: portal
foliage_variant: toxic
mutation_variant: random
behaviour_variant: crazy
