map_width: 20
map_height: 10
starting_foliage: 50
energy_gain: 5
daily_foliage_growth: 2
starting_animals: 2
starting_energy: 30
min_procreation_energy: 15
procreation_energy_loss: 10
min_mutations: 0
max_mutations: 5
genome_length: 32

map_variant: globe
foliage_variant: equator
mutation_variant: random
behaviour_variant: predestined
